version: '3'

services:
  GRPCService:
    image: GRPC-app
    build:
      context: .
      dockerfile: Dockerfile  # Path to your Dockerfile
    ports:
      - "50050:50050"
    environment:
      - PORT=50050  # Set the PORT environment variable
      - GRPCKEY=MULTI # Set the GRPC KEY environment variable
    networks:
      - RYANCOAL-network # Optionally, you can define a custom network

networks:
  RYANCOAL-network:  # Optionally, create a custom network


  


